ignore:
  - "**/__init__.py"
  - "pylibczi/tests"
  - "pylibczi/c_tests"
  - "pylibczi/docs"
  - "pylibczi/bin"
  - "pybind11"
  - "_pylibczi/*"
  - "libCZI"
  - ".github"
  - "cmake-build-debug"
  - "_build"
