ignore:
  - "**/__init__.py"
  - "pylibczi/tests"
  - "pylibczi/bin"
  - "pylibczi/exceptions.py"
  - "pylibczi/types.py"
  - "pybind11"
  - "libCZI"
  - ".github"
  - "cmake-build-debug"
  - "_build"
