name: Docs

on:
  push:
    branches:
      - rename/aicspylibczi
    tags:
      - 'docs'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build & Publish Docs
        uses: JacksonMaxfield/github-pages-deploy-action-python@master
        env:
          BUILD_DOCS: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: rename/aicspylibczi
          BRANCH: gh-pages
          FOLDER: cmake-build-debug/docs/html
          BUILD_SCRIPT: pip install .[dev] && mkdir cmake-build-debug && cd cmake-build-debug && cmake .. && cmake --build . --target docs
