name: Docs

on:
  push:
    branches:
      - feature/Publish

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        env:
          GHREPO: "pylbiczi"
          REPO_PATH: "https://${{secret.ACCESS_TOKEN}}@github.com/${{GHREPO}}.git"
          run: |
            python -m pip install --upgrade pip
            pip install sphinx
            pip install sphinx-rtd-theme
            export GHPAGES=[ "$(git ls-remote --heads "$REPOSITORY_PATH" "gh-pages" | wc -l)" -eq 0 ]
          shell: bash
        - name: Create gh-pages
          if: $GHPAGES
          run: |
            echo "Creating remote branch ${BRANCH} as it doesn't exist..."
            git checkout "${BASE_BRANCH:-master}"
            git checkout --orphan $BRANCH
            git rm -rf .
            touch README.md
            git add README.md
            git commit -m "Initial ${BRANCH} commit"
            git push $REPOSITORY_PATH $BRANCH
      - name: Generate Docs
        env:
          CC: clang
          CXX: clang++
          BUILD_HOME: cmake-build-debug
          FOLDER: docs/html
          BRANCH: gh-pages
          GHREPO: "pylbiczi"
          REPO_PATH: "https://${{secret.ACCESS_TOKEN}}@github.com/${{GHREPO}}.git"
          run: |
            mkdir -p $BUILD_HOME/$FOLDER
            git clone $REPO_PATH $BUILD_HOME/$FOLDER
            pushd .
            cd $BUILD_HOME/$FOLDER
            git checkout $BRANCH
            popd
            cd $BUILD_HOME
            cmake ..
            cmake --build . --target docs
            cd $FOLDER
            touch .nojekyll
            git commit -a -m "Deploying branch to gh-pages" --quiet
            git push $REPOSITORY_PATH ${BRANCH}
          shell: bash
