on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 10 * * 1

name: C++ Master Build
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [llvm, gnu]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: llvm build and test
        if: matrix.compiler == 'llvm'
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir ./cmake-build-debug
          cd cmake-build-debug
          cmake ../
          cmake --build .
        shell: bash
      - name: gnu build and test
        if: matrix.compiler == 'gnu'
        env:
          CC: gcc
          CXX: g++
          run: |
            mkdir ./cmake-build-debug
            cd cmake-build-debug
            cmake ../
            cmake --build .
          shell: bash
