on: [push, pull_request]
name: C++ Build
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: build with cmake
        run: |
          mkdir ./cmake-build-debug
          cd cmake-build-debug
          cmake ../
          make
      - name: run C++ tests
        run: |
          cd ./cmake-build-debug/c_tests/
          ./test_libczi_c++_extension
