on: [push, pull_request]
name: C++ Build
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: build and test
        run: |
          mkdir ./cmake-build-debug
          cd cmake-build-debug
          cmake ../
          cmake --build .
        if: !startWith( ${{ matrix.os }} , 'windows')
          env:
            CC: clang
            CXX: clang++
        shell: bash
