on:
  push:
    branches:
      - master
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 18:00:00 UTC (Monday at 10:00:00 PST)
    - cron: '0 18 * * 1'

name: C++ Master Build
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: build with cmake
        run: |
          which clang
          export CC=clang
          export CXX=clang++
          mkdir ./cmake-build-debug
          cd cmake-build-debug
          cmake ../
          make
      - name: run C++ tests
        run: |
          cd ./cmake-build-debug/c_tests/
          ./test_libczi_c++_extension
