on: [push, pull_request]
name: C++ Build
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [llvm, gnu]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: build and test
        env:
          CC: clang
          CXX: clang++
        if: matrix.compiler == 'gnu'
          CC: gcc
          CXX: g++
        run: |
          mkdir ./cmake-build-debug
          cd cmake-build-debug
          cmake ../
          cmake --build .
        shell: bash
