name: Wheel build test
on: push

jobs:
  wheel-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [macOS-10.15]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Wheel
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          source ~/.bashrc
          conda create -y -n builder python=3.8
          conda activate builder
          export SDKROOT=/Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
          export MACOSX_DEPLOYMENT_TARGET=10.9
          which python
          pip install wheel
          python setup.py bdist_wheel
          ls dist/*
