name: Python package build and publish
on:
  push:
    branches:
      - 'release/aicspylibczi'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Build manylinux Python wheels
        uses: allen-cell-animated/python-wheels-manylinux-build@v1.1
        with:
          python-versions: 'cp36-37m cp37-cp37m cp38-cp38'
          build-requirements: 'cython numpy make cmake==3.17.3 twine wheel'
      - name: Upload Files
        run: |
          twine upload --repository-url https://upload.pypi.org/legacy/ -u aicspypi -p '${{ secrets.PYPI_TOKEN }}' dist/*manylinux2010*.whl
