name: Python package build and publish
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1
        with:
          python-versions: 'cp37-cp37m'
          build-requirements: 'cython numpy make cmake==3.17.3 twine wheel'
          pre-build-command: 'bash ./scripts/docker_setup.sh'
      - name: List Files
        run: |
          ls dist/*-manylinux*.whl
