name: Python package build and publish
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
          pip install cmake==3.13.3
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2010_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m'
          build-requirements: 'cython numpy'
      - name: List Files
        run: |
          dist/*-manylinux*.whl
