name: Wheel Publish
on:
  push:
    branches:
      - 'release/aicspylibczi'

jobs:
  wheel-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: Upload Wheel
        run: |
          pip install twine
          pip install --user --upgrade twine
          twine upload --repository-url https://upload.pypi.org/legacy/ -u aicspypi -p '${{ secrets.PYPI_TOKEN }}' dist/*
