on: [pull_request]
name: Python Build PR
jobs:
  python-test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install aicspylibczi
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Test with pytest
        run: |
          pytest -n1 --cov-report xml --cov=aicspylibczi aicspylibczi/tests
      - name: Build the sdist
        run: pipx run build --sdist
      - name: Check install from sdist
        run: pip install --force-reinstall --no-index --find-links=./dist aicspylibczi

      - name: Upload codecov
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Lint with flake8
        run: |
          flake8 aicspylibczi --count --verbose --max-line-length=127 --show-source --statistics
