on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 10 * * 1

name: Python Build, Test, & Lint
jobs:
  python-test:
    name: Python Build & Test Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Test with pytest
        run: |
          pytest --cov-report xml --cov=pylibczi pylibczi/tests
          codecov -t ${{ secrets.CodeCovKey }}
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Lint with flake8
        run: |
          flake8 aicsimageio --count --verbose --max-line-length=127 --show-source --statistics
